### ISSUE TITLE
Upgrade to the latest wallet core

### ISSUE THREAD

**Issue by DegenTim** [degenwallet/react-native-wallet-core#12]
https://github.com/trustwallet/wallet-core/releases/tag/3.1.8

**Comment by Walletsuppport** [comment]
> https://github.com/trustwallet/wallet-core/releases/tag/3.1.8

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
